/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as xPadSol from "./XPad.sol";
export type { xPadSol };
export type { Factory } from "./Factory";
export type { Pair } from "./Pair";
export type { Router } from "./Router";
